name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps::boom:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: cd src

      - name: Install packages
        run: yarn install

      - name: Build project
        run:
          - yarn gatsby build
          - node ./compileSHAs.js

      - run: cp -r ./src/public/* ./target/

      - name: Deploy playbook
        uses: actions/ansible-playbook-docker-action@2.8.5
        with:
          playbookName: 'ansible/playbook.yml'
